application: zufont
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(n/[^/]+|f/[A-Za-z0-9_=-]+(/[^/]*)?)
  script: f.app

- url: /logout
  script: logout.app

- url: /(|upload|delete/[A-Za-z0-9_=-]+)
  script: admin.app
  login: admin

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
